# db-externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-sm
    kind: ClusterSecretStore
  target:
    name: db-secret
  data:
    - secretKey: DB_HOST
      remoteRef: { key: prj/prod/db, property: DB_HOST }
    - secretKey: DB_NAME
      remoteRef: { key: prj/prod/db, property: DB_NAME }
    - secretKey: DB_USER
      remoteRef: { key: prj/prod/db, property: DB_USER }
    - secretKey: DB_PASS
      remoteRef: { key: prj/prod/db, property: DB_PASS }