apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: app
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector: { matchLabels: { app: nginx-frontend } }
  template:
    metadata: { labels: { app: nginx-frontend } }
    spec:
      nodeSelector: { workload: frontend }
      tolerations:
        - key: "workload"
          value: "frontend"
          effect: NoSchedule
      containers:
        - name: nginx
          image: 857305036087.dkr.ecr.ap-northeast-2.amazonaws.com/ecr_nginx:v0.11
          ports: [ { containerPort: 80 } ]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
  namespace: app
spec:
  selector: { app: nginx-frontend }
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80