apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimidaily-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/woduf1020/MiMiDaily.git   # ← 본인 레포
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground